base: 'http://cms24.s2310456034.student.kwmhgb.at/'
languages:
  -
    title: Deutsch
    enabled: true
    languageId: 0
    base: /
    locale: de_DE
    navigationTitle: Deutsch
    flag: at
    hreflang: ''
    websiteTitle: 'Girlie Ski Demo Team'
  -
    title: English
    enabled: true
    locale: en_US
    hreflang: en-Us
    base: /en/
    websiteTitle: 'Girlie Ski Demo Team'
    navigationTitle: EN
    fallbackType: strict
    fallbacks: ''
    flag: en-us-gb
    languageId: 1
rootPageId: 1
websiteTitle: GirlieSkiDemoTeam
